### ISSUE TITLE
Wobbly does not correctly set matches on the end of scenes or the end of the clip

### ISSUE THREAD

**Issue by wiwaz** [Setsugennoao/Wobbly#15]
Right now whether wobbly decides to place a B match at the end of a section or not depends on the mic value, this is not correct behavior. When the pattern of a scene is decided and the final frame ends with an N match, Wobbly should always be converting this N match to be a B match, regardless of what the mic is.

Additionally, Wobbly seems to always place a C match at the end of the clip. Once again this behavior is incorrect as if the pattern the section uses causes the clip to end with an N match then it should end with a B match instead.

**Comment by wiwaz** [comment]
After thinking this over we probably want a more robust solution than just "replace N with B at scene end" as it's not guaranteed that the end of a section is necessarily accurate. So instead, I suppose the mic solution can be kept but with C matches excluded (i.e. never replace an N match with C at the end of a section, always use B)

**Comment by Setsugennoao** [comment]
Fixed in https://github.com/Setsugennoao/Wobbly/compare/7c5e125a7e2265da42ba35f0fdbe072a5946bbc8...b04bae897e18522a347f8de274f590da1bfd5ab5
