### ISSUE TITLE
Chroma IVTC methods

### ISSUE THREAD

**Issue by LightArrowsEXE** [Setsugennoao/Wobbly#17]
There are sources out there with mismatched chroma that are difficult to handle in wobbly. Having additional methods to fix these would be nice. This issue also serves as a place to discuss ideal methods.

I think being able to pick individual planes to process would be a great start, including a setting to process to apply it to every field (this should be the default to match current expected behaviour). An extra menu specific to this may need to be made, and existing filters in wobbly probably need to be updated to support this too (or else default back to working on all planes to not break existing workflows)

Discuss.

**Comment by Setsugennoao** [comment]
This looks very out of scope and complex to implement. You could however passa .vpy and ShufflePlane, processing each plane separetely.
